name: Move PR to Project Board using GH CLI

on:
  pull_request:
    types: [opened, ready_for_review, closed]

jobs:
  update_project:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Move PR to 'In Progress' when opened
        if: github.event.action == 'opened'
        run: |
          PR_ID=$(gh pr view ${{ github.event.pull_request.number }} --repo tannguyen23/nestjs-ecommerce-api --json id --jq '.id')
          echo "PR ID is $PR_ID"
          gh project item-edit \
            --id $PR_ID \
            --project-id PVT_kwHOA-q6RM4AwdvH \
            --field-id PVTSSF_lAHOA-q6RM4AwdvHzgmuwfA \
            --single-select-option-id 47fc9ee4

      - name: Move PR to 'In Review' when marked ready
        if: github.event.action == 'ready_for_review'
        run: |
          PR_ID=$(gh pr view ${{ github.event.pull_request.number }} --repo tannguyen23/nestjs-ecommerce-api --json id --jq '.id')
          echo "PR ID is $PR_ID"
          gh project item-edit \
            --id $PR_ID \
            --project-id PVT_kwHOA-q6RM4AwdvH \
            --field-id PVTSSF_lAHOA-q6RM4AwdvHzgmuwfA \
            --single-select-option-id df73e18b

      - name: Move PR to 'Done' when closed
        if: github.event.action == 'closed'
        run: |
          PR_ID=$(gh pr view ${{ github.event.pull_request.number }} --repo tannguyen23/nestjs-ecommerce-api --json id --jq '.id')
          echo "PR ID is $PR_ID"
          gh project item-edit \
            --id $PR_ID \
            --project-id PVT_kwHOA-q6RM4AwdvH \
            --field-id PVTSSF_lAHOA-q6RM4AwdvHzgmuwfA \
            --single-select-option-id 98236657
