name: Move PR to Project Board

on:
  pull_request:
    types: [opened, ready_for_review, closed]

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to 'in_progress' when opened
        if: github.event.action == 'opened'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/tannguyen23/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labeled: 'in_progress'

      - name: Move PR to 'in_review' when marked ready
        if: github.event.action == 'ready_for_review'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/tannguyen23/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labeled: 'in_review'

      - name: Move PR to 'done' when closed
        if: github.event.action == 'closed'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/tannguyen23/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labeled: 'done'
